name: ESLint

on:
  push:
    branches:
      - "main"
      - "feature/APIP-1057"
  pull_request:
    branches:
      - "main"
      - "feature/APIP-1057"

jobs:
  eslint:
    name: Run ESLint checks
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run eslint
        continue-on-error: false